### PR TITLE
Lg add structs

### PR DESCRIPTION
**Pull request by Leo-Gilbert**
Added structs for itinerary and model. Also created itinerary service directory. Ticket is TT-31 (Sorry I forgot the branch naming conventions)

### CODE REVIEW

**Review by AbdulTur — APPROVED** [review]
LGTM ig, i didnt really look tho

**Comment by AbdulTur** [comment]
I will merge after @MiguelPond  does testing and @jordyob03  approves

**Review by jordyob03 — COMMENTED** [review]
Looks great to me!

**Review by jordyob03 — APPROVED** [review]

**Review by WyrdWyn4 — APPROVED** [review]
Looks good Boss, Approved👍

**Pull request merged**
