### PR TITLE
 TT-24-njrc-Create-Profile Added Create and Update

### PR DESCRIPTION
**Pull request by noahjrc**
only backend code so far, Abdul please make sure this works, not linked to frontend yet

### CODE REVIEW

**Comment by WyrdWyn4** [comment]
@noahjrc I think you added in db_data/ Would it be possible for you to uncommit that folder and everything inside it? Thank you : )

**Comment by AbdulTur** [comment]
@WyrdWyn4  when u run ur stuff did u have a db_data folder for your db files? because my database stuff is stored in pgdata at the root

**Comment by WyrdWyn4** [comment]
> @WyrdWyn4  when u run ur stuff did u have a db_data folder for your db files? because my database stuff is stored in pgdata at the root
> 

Yeap, I've got a db_data folder, and for someone running the database for the first time, it should come up automatically. 

I'm kinda confused on how your stuff is in pgdata. Let me look at the code and see what's going on.

**Comment by WyrdWyn4** [comment]
> > Yeap, I've got a db_data folder, and for someone running the database for the first time, it should come up automatically.
> > I'm kinda confused on how your stuff is in pgdata. Let me look at the code and see what's going on.
> 
> Hmmmm thats weird, my db files are stored in pgdata in following at the root
> 

Sorry, I just checked. You're right, I had old data in db_data, and I thought it was new data being populated. Apologies for the confusion.

**Comment by AbdulTur** [comment]
> > > Yeap, I've got a db_data folder, and for someone running the database for the first time, it should come up automatically.
> > > I'm kinda confused on how your stuff is in pgdata. Let me look at the code and see what's going on.
> > 
> > 
> > Hmmmm thats weird, my db files are stored in pgdata in following at the root
> 
> Sorry, I just checked. You're right, I had old data in db_data, and I thought it was new data being populated. Apologies for the confusion.

So is your data now being stored in pgdata?

**Pull request closed without merging**
