### PR TITLE
User authentication and profile creation UI

### PR DESCRIPTION
**Pull request by allymreid**
Tickets: https://ece6400triptailor.atlassian.net/browse/TT-28 & https://ece6400triptailor.atlassian.net/browse/TT-29

Added 4 pages:
**Log In (First page seen upon startup at http://localhost:3000)**
image

**Sign Up (Accessible by pressing sign up button on Log In page, or at http://localhost:3000/sign-up)**
image

**Initial Profile Creation (Accessible after signing up and submitting form, or at http://localhost:3000/profile-creation)**
- Min of three tag selection
- Multiple language selections allowed
- One country selection only
image 
image

**Account Settings (not routed yet, can't currently be displayed without updating App.js)**
image

### CODE REVIEW

**Review by AbdulTur — CHANGES_REQUESTED** [review]
Looks awesome. Slight request, would you be able to move the styles into their own styles.css files and import them from the styles folder? Also this is unimportant and if it takes too long then no need, but in sign up page is it possible to add a retype password box below the password box. Nonetheless great job

**Comment by allymreid** [comment]
> Looks awesome. Slight request, would you be able to move the styles into their own styles.css files and import them from the styles folder? Also this is unimportant and if it takes too long then no need, but in sign up page is it possible to add a retype password box below the password box. Nonetheless great job

@AbdulTur Good ideas, just added them. Thanks!

**Review by AbdulTur — APPROVED** [review]
LGTM!! Great work

**Review by jordyob03 — APPROVED** [review]
Looks great thank you both!

**Pull request merged**
