### PR TITLE
Created the auth service, signin and signup feature, added PGAdmin

### PR DESCRIPTION
**Pull request by AbdulTur**
# Created the Auth Service
## Jira Tickets
Signup: https://ece6400triptailor.atlassian.net/browse/TT-16
Signin: https://ece6400triptailor.atlassian.net/browse/TT-17

### Frontend
Created AuthAPI file in where the auth service port is taken. The AuthAPI is imported into UserLogin and UserSignup page files where they are used to send post requests to the auth service. Further, created protected routes to handle session tokens that are generated when user signs up or logs in, the tokens are stored in local. In the profile page added a logout button that deletes the token from local storage and navigates to login. If user does not have a token, created protected routes, wrapped the profile, to make sure user does not have access to pages without the token, and redirects to login. 
### Backend
Created auth service code. Created backend logic to handle signin and signup api methods. Further created logic to generate token and send to frontend. User information is stored in the db. 

### PGAdmin
Modified the compose file to connect PGAdmin to the db, PGAdmin is a tool to view the db in gui format, on port 8082:80, go to port, put in following credentials 
`PGADMIN_DEFAULT_EMAIL: admin@admin.com ` 
 `PGADMIN_DEFAULT_PASSWORD: admin`

Right click on server, press on register server.
Give it whatever name u want. in the connection tab
write db for top option
for user: postgres
for password: password
maintnance: postgres

then select connect.

## Testing
Pull branch, run the docker compose file, run the auth service main.go file, run the frontend. Do tests, can observe additions to db on pgadmin

### CODE REVIEW

**Comment by AbdulTur** [comment]
@MiguelPond  can u do the testing please

**Review by noahjrc — APPROVED** [review]
LGTM

**Review by Leo-Gilbert — APPROVED** [review]
LGTM

**Comment by AbdulTur** [comment]
I will merge after @MiguelPond does testing and @jordyob03 approves

**Review by allymreid — APPROVED** [review]

**Review by jordyob03 — APPROVED** [review]
LGMT

**Review by WyrdWyn4 — APPROVED** [review]
Good Job Boss 👍

**Comment by MiguelPond** [comment]
Followed instructions, works great. Inputs are registering in pgadmin. Non-functionally, seems performant when spamming the buttons.

**Pull request merged**
