### PR TITLE
Search Bar, User Dashboard, and basic Home Page

### PR DESCRIPTION
**Pull request by allymreid**
_All of these pages need to be integrated with backend_

### User Dashboard
image

### Search Results
image

### Home Page
image

### CODE REVIEW

**Review by AbdulTur — APPROVED** [review]
LGTM

**Comment by Leo-Gilbert** [comment]
I tested @AbdulTur 's changes (adding the search API call) and it works fine for me. I did some testing on the itinerary creation and it didn't create any API request. Is this expected? I'm not sure the level of functionality we are going for here. All of the other pages LGTM though. If someone can confirm this itinerary creation behaviour I can approve

**Comment by AbdulTur** [comment]
> I tested @AbdulTur 's changes (adding the search API call) and it works fine for me. I did some testing on the itinerary creation and it didn't create any API request. Is this expected? I'm not sure the level of functionality we are going for here. All of the other pages LGTM though. If someone can confirm this itinerary creation behaviour I can approve

Itinerary is not implemented yet, i tested the search with the test query u provided

**Comment by allymreid** [comment]
Yeah itinerary is not implemented but pretty sure Jordyn is doing that on her branch

**Review by Leo-Gilbert — APPROVED** [review]
lgtm

**Pull request merged**
