### PR TITLE
Tt 75 lg search alternate

### PR DESCRIPTION
**Pull request by Leo-Gilbert**
Modified version of original searching algorithm. It basically takes a search string, compares the entire string against the title field of the itineraries, and then splits the string into individual tokens, and compares each token against every field in the entire Itinerary Table. Also includes a price field for filtering itineraries <= the specified price.

yes this is computationally expensive but it will look good in the demo.

example test case:

curl "http://localhost:8084/search?q=Nightlife&price=200"
curl "http://localhost:8084/search?q=Adventure"
curl "http://localhost:8084/search?q=Exploring%20Lahore's%20Old%20City

### CODE REVIEW

**Comment by AbdulTur** [comment]
bro our aws bill gonna be high

**Comment by AbdulTur** [comment]
can u merge main and resolve conflicts please

**Comment by WyrdWyn4** [comment]
> can u merge main and resolve conflicts please

Yeap, I'm on it

**Review by AbdulTur — APPROVED** [review]
LGTM!! Tested, everything seems to be working, have done a mini regression test as well, all other features seem to be fine. Great job on the algo

**Review by MiguelPond — APPROVED** [review]
Tested - Observations:

Once redirected to /search-results, this shit slaps

**Review by WyrdWyn4 — APPROVED** [review]
Great Job!

**Pull request merged**
