### PR TITLE
Tt 58 mdp auth service to docker

### PR DESCRIPTION
**Pull request by MiguelPond**
https://ece6400triptailor.atlassian.net/browse/TT-58?atlOrigin=eyJpIjoiMzBjOGJjYTVhYzU1NGJmMThjNWFmMmI2MjEwZDU0MDAiLCJwIjoiaiJ9

Added Auth-service container, restructured services to be able to each have their own container

### CODE REVIEW

**Comment by AbdulTur** [comment]
so we are continuing with the main service?

**Comment by WyrdWyn4** [comment]
Good work @MiguelPond, looks good to me. 😎

Sorry this might be a stupid question, but is there a way to use short form addresses, like `db /auth-service/internal/db"` rather than `db "github.com/jordyob03/TripTailor/backend/services/auth-service/internal/db"`.

I feel like that would help reduce complexity, and you can readily read and tell where the file is from.

**Comment by WyrdWyn4** [comment]
> so we are continuing with the main service?

From what I understand, we're storing all the db code there, and we're going to get rid of that later?
Idk, I went through your and Miguel's convo on discord, and that's sort of what I understood.

**Comment by MiguelPond** [comment]
@AbdulTur Using the long-form addresses was preferred wherever I was looking online, I kind of like it cause of how verbose it is. Otherwise if we are strictly keeping all dependencies under each microservice dir then it's not nearly as important

**Comment by MiguelPond** [comment]
@AbdulTur Does main-service still actively do something that hasn't been replaced yet?

**Comment by AbdulTur** [comment]
> @AbdulTur Does main-service still actively do something that hasn't been replaced yet?

As far as I see it does nothing other than creating tables, after which it serves no purpose and takes up a container. Unless there is something I don't see

**Comment by WyrdWyn4** [comment]
> @AbdulTur Using the long-form addresses was preferred wherever I was looking online, I kind of like it cause of how verbose it is. Otherwise if we are strictly keeping all dependencies under each microservice dir then it's not nearly as important

I see, that sounds good. Thanks for the explanation.

**Review by WyrdWyn4 — APPROVED** [review]
Good Job!

**Comment by MiguelPond** [comment]
@AbdulTur If you wouldn't mind, can you pull it and make sure your docker-compose goes smoothly?

**Comment by AbdulTur** [comment]
> @AbdulTur If you wouldn't mind, can you pull it and make sure your docker-compose goes smoothly?

Will do, won't be today but will do. Also want to discuss this tomorrow

**Review by jordyob03 — APPROVED** [review]

**Pull request merged**
