### PR TITLE
TT 62 LG searching

### PR DESCRIPTION
**Pull request by Leo-Gilbert**
# Summary

Added bare bones implementation for a searching service. The structure closely models the auth service

- Implemented search functionality for itineraries based on location (city and country).

---

## Changes

- [x] Added /search: This endpoint accepts country and city as query parameters and returns the list of matching itineraries using SQL.
- [x] Connected the service to PostgreSQL for storing and retrieving itineraries.
- [x] Miguel has added the Dockerfile
- [x] Abdul has added some basic front end code (**Search.js, SearchAPI.js**)  

---

## Implementation Details

Axios Integration (Frontend):
	•	The frontend uses Axios to send a GET request with query parameters **(Search.js)**:
                `const response = await searchAPI.get('/search', { params: { country, city } });`

---

## How to Test

To use the service locally, you will need to have sample data in your **_itineraries_** and _**users**_ tables. The queries i used are located in the **test** folder. **Do not try to run these queries from your IDE**.  Instead, copy them and run them through pgadmin.

Then, run the service:
   ```bash
   docker-compose up -d search-service
```
Enter Search (make sure this search is valid given the data you have in your tables) @ http://localhost:3000/search
image

Then view the response:
image

### CODE REVIEW

**Comment by AbdulTur** [comment]
I love the commit message of removed shit

**Comment by AbdulTur** [comment]
The code from my read through looks good, I will test it in a bit, also love the PR description

**Comment by MiguelPond** [comment]
Alongside Leo, I added a test for the Query using sqlmock, and have the docker containers run the test on rebuild

**Review by allymreid — APPROVED** [review]
LGTM from a frontend perspective. 1 question though, can users search by only country by leaving the city field blank, or is city mandatory? This is prob obvious in the code somewhere but idk go well enough

**Comment by AbdulTur** [comment]
> LGTM from a frontend perspective. 1 question though, can users search by only country by leaving the city field blank, or is city mandatory? This is prob obvious in the code somewhere but idk go well enough

Seems to be mandatory

**Review by AbdulTur — APPROVED** [review]
LGTM

**Review by WyrdWyn4 — APPROVED** [review]
Good Job Boss!

**Pull request merged**
