### PR TITLE
TT-24-njrc-Create-Profile

### PR DESCRIPTION
**Pull request by noahjrc**
Completed the profile create and update, with proper database connections, check to make sure working, as I will be away this weekend

### CODE REVIEW

**Review by AbdulTur — CHANGES_REQUESTED** [review]
Can you delete the db_data please, just delete the folder, commit and push

**Comment by WyrdWyn4** [comment]
> Can you delete the db_data please, just delete the folder, commit and push

I sat with @noahjrc and tried doing that in the morning. Didn't work out. I think he'll have to copy the files, create a new branch, and a new PR, and then work with it.

**Comment by AbdulTur** [comment]
> > Can you delete the db_data please, just delete the folder, commit and push
> 
> I sat with @noahjrc and tried doing that in the morning. Didn't work out. I think he'll have to copy the files, create a new branch, and a new PR, and then work with it.

Let me try

**Comment by AbdulTur** [comment]
Finally my GitHub is not crashing anymore when i go to see files changed

**Review by AbdulTur — APPROVED** [review]
LGTM Good job

**Comment by WyrdWyn4** [comment]
> LGTM Good job

alt text

**Comment by AbdulTur** [comment]
> I added a Dockerfile, updated conn string and appended the docker-compose.

Did u test it?

**Comment by MiguelPond** [comment]
@AbdulTur Boots fine, prints no errors and serves on 8085, what's the testing procedure?

**Comment by AbdulTur** [comment]
> @AbdulTur Boots fine, prints no errors and serves on 8085, what's the testing procedure?

More so meant code works, will pull and test just in case

**Comment by MiguelPond** [comment]
How do I test the code through the application?

**Comment by AbdulTur** [comment]
> How do I test the code through the application?

Regression testing, except, without scripts, what i am gonna do for example is run frontend and backend and just test the whole application to make sure everything works fine and is ready to be merged.

**Comment by AbdulTur** [comment]
Everything works probably good for merge, will have to merge after Allys PR

**Review by WyrdWyn4 — APPROVED** [review]
LGTM, Great Job!

**Pull request merged**
