### PR TITLE
Query Tags for Feed purposes

### PR DESCRIPTION
**Pull request by MitchRoberts**
- Feed should display filtered itineraries based on user tags selected on the profile creation screen. 
- Feed itins should update after updating tags in profile settings
- Clicking filtering buttons on top of the homepage should display Itins according to AND logic (ie. if you select "Teenagers" and "Young Adults" itins with both those tags will be shown)

### CODE REVIEW

**Review by WyrdWyn4 — APPROVED** [review]
Great Job Boss!

**Review by MiguelPond — APPROVED** [review]
Goat

**Comment by MiguelPond** [comment]
Add valid tags to testuser 

Undo that last commit waleed

**Comment by MiguelPond** [comment]
LGTM (Looks Grippy to Me)

**Pull request merged**
