### PR TITLE
Image Storage Implementation

### PR DESCRIPTION
**Pull request by WyrdWyn4**
### Ticket: TT-65

# Changes
## 1. `DBModels`
 - Removed duplicate code in DBModels
 - The main-service/internal/db/models will be used to store the database code, and everyone can copy from here.
## 2. `User-db.go`
 - Added Profile and Cover images for user
 - Added logic to update and remove these images
## 3. `Post-db.go`
 - Added Post Images
 - Added functionality to add or remove these images
## 4. `Event-db.go`
 - Added Event Images
 - Added functionality to add or remove these images
## 5. `Database.go`
 - Updated CreateAllTables and DeleteAllTables functions to add Images table
## 6. `Images-db.go`
 - Created a new table for Images
 - Current columns are:
    - `ImageId`: Numeric unique serial Id
    - `ImageData`: Image Data stored as a string of 'Bytea' type
    - `Metadata`: Tells how the image is being used {profile, cover, event, post}
 - Added the following functions:
    - `InitializeImageTable`: Initializes the base Profile photo and base Cover photo with Ids 1 and 2
    - `CreateImageTable`: Creates the Image Table
    - `AddImage`, `GetImage`, `RemoveImage`: CRUD with Images
    - `AddImageMetaData`, `RemoveImageMetaData`: CRUD with Metadata
    - `ImageToByte`: Can convert image at `imagepath` to storable byte
    - `WebImageToByte`: Can convert image at `imageurl` to storable byte
    - `ByteToImage`: Can convert bytes to image, and store at `outputPath`
 - Added Image Handler
    - Images can now be seen at http://localhost:8080/images/{id}

# Notes
 - Base Profile photo is stored at http://localhost:8080/images/1
 - Base Cover photo is stored at http://localhost:8080/images/2
 - Run the code and open http://localhost:8080/images/4 : )

### CODE REVIEW

**Review by Leo-Gilbert — COMMENTED** [review]
So we decided to store the image in binary as opposed to using that imgur api you were talking about? I trust your judgement, just want to confirm this is what we are doing

**Comment by WyrdWyn4** [comment]
> So we decided to store the image in binary as opposed to using that imgur api you were talking about? I trust your judgement, just want to confirm this is what we are doing

Yessir

**Comment by Leo-Gilbert** [comment]
I was talking to dan and he said we could just have a folder in our app with all images we would use in our testing and demos, and then store the paths to these images in the database. IMO this makes slightly more sense then storing the images as binary. Realistically there is no good way to do this without using AWS or something. What do you guys think? @WyrdWyn4 @MiguelPond @jordyob03 @AbdulTur

**Comment by AbdulTur** [comment]
> I was talking to dan and he said we could just have a folder in our app with all images we would use in our testing and demos, and then store the paths to these images in the database. IMO this makes slightly more sense then storing the images as binary. Realistically there is no good way to do this without using AWS or something. What do you guys think? @WyrdWyn4 @MiguelPond @jordyob03 @AbdulTur

We could do that for demo or this course if we really need to, but i think image upload is one of our core features. Besides for bytes idk if we need aws

**Comment by WyrdWyn4** [comment]
> I was talking to dan and he said we could just have a folder in our app with all images we would use in our testing and demos, and then store the paths to these images in the database. IMO this makes slightly more sense then storing the images as binary. Realistically there is no good way to do this without using AWS or something. What do you guys think? @WyrdWyn4 @MiguelPond @jordyob03 @AbdulTur

The scene is, storing the images as binary sounds kinda scary, but I actually implemented two functions:
 - `ImageToByte:` Can convert image at imagepath to storable byte
 - `WebImageToByte:` Can convert image at imageurl to storable byte

All you have to do is load the image like the following:

```
image1 := db.Image{
	ImageData: db.WebImageToByte("https://wallpapercave.com/wp/wp8484597.jpg"),
}

id, err := db.AddImage(DB, image1)
```

This would return `id`, and all images can be accessed at http://localhost:8080/images/{id}

I think this will make life better - *No one has to, at any point, have to handle or deal with **ANY** binary*

What do you think Boss @Leo-Gilbert @AbdulTur

**Comment by Leo-Gilbert** [comment]
After thinking about it, I feel this is still our best option even though it is slightly cumbersome. Looks like you have put a lot of thought into streamlining and optimizing it. Nice work.

LGTM

**Review by Leo-Gilbert — APPROVED** [review]

**Comment by AbdulTur** [comment]
@Leo-Gilbert @WyrdWyn4  I did a bit of reading, and typically the conversion happens in frontend actually, JS has built in tools apparently, and if not, there 100% exists number of packages that do that, so i think it will be a lot simpler than we thought. The conversion will happen in frontend, the blob will be sent through api and stored in db, retrieved and converted back to an image in the frontend

**Comment by WyrdWyn4** [comment]
> @Leo-Gilbert @WyrdWyn4 I did a bit of reading, and typically the conversion happens in frontend actually, JS has built in tools apparently, and if not, there 100% exists number of packages that do that, so i think it will be a lot simpler than we thought. The conversion will happen in frontend, the blob will be sent through api and stored in db, retrieved and converted back to an image in the frontend

Oh yeah, there would 100% be stuff like that. I didn't want to make @allymreid and @napierce go mad dealing with binary in the front end, so I created the `imagehandler`, which basically outputs all images at http://localhost:8080/images/{id}

Even the image handler doesn't use any JS, but it uses the http.ResponseWriter to write out the image on the link

**Comment by AbdulTur** [comment]
> > @Leo-Gilbert @WyrdWyn4 I did a bit of reading, and typically the conversion happens in frontend actually, JS has built in tools apparently, and if not, there 100% exists number of packages that do that, so i think it will be a lot simpler than we thought. The conversion will happen in frontend, the blob will be sent through api and stored in db, retrieved and converted back to an image in the frontend
> 
> Oh yeah, there would 100% be stuff like that. I didn't want to make @allymreid and @napierce go mad dealing with binary in the front end, so I created the `imagehandler`, which basically outputs all images at [http://localhost:8080/images/{id}](http://localhost:8080/images/%7Bid%7D)
> 
> Even the image handler doesn't use any JS, but it uses the http.ResponseWriter to write out the image on the link

Nah i can do that, I actually did some binary conversion at Angler, although that was for data compression, but still same principle, just a library and that's it

**Comment by WyrdWyn4** [comment]
> Nah i can do that, I actually did some binary conversion at Angler, although that was for data compression, but still same principle, just a library and that's it

Oh lol, that's good to hear, I didn't know if it'd be a burden. I guess the `imagehandler` can still function as a quick debug tool nonetheless.

**Review by AbdulTur — APPROVED** [review]
LGTM well done

**Pull request merged**
