### PR TITLE
Itinerary reformatting

### PR DESCRIPTION
**Pull request by allymreid**
Removed estimated cost and split location into city and country on itinerary creation page.

### CODE REVIEW

**Review by WyrdWyn4 — COMMENTED** [review]
Looks good to me Boss. Great Job 👌


@AbdulTur @jordyob03 just to confirm we're on the same page, the price of an itinerary will be determined in the backend by looping over and summing the costs of the individual events right? Using the `db.UpdateItineraryPrice()` function

**Comment by WyrdWyn4** [comment]
@allymreid @napierce @AbdulTur @jordyob03 @MitchRoberts Every Itinerary is linked to a Post. Therefore, we need to create a Post as well whenever we're creating an Itinerary.

The only crucial piece of data that we are missing to create the Post is the Username.

Therefore, I believe that the CreateItinRequest struct being passed from the frontend to the backend must contain the username, so that we can use that data to create a Post.

Thoughts?

**Comment by AbdulTur** [comment]
> @allymreid @napierce @AbdulTur @jordyob03 @MitchRoberts Every Itinerary is linked to a Post. Therefore, we need to create a Post as well whenever we're creating an Itinerary.
> 
> The only crucial piece of data that we are missing to create the Post is the Username.
> 
> Therefore, I believe that the CreateItinRequest struct being passed from the frontend to the backend must contain the username, so that we can use that data to create a Post.
> 
> Thoughts?

Thats already being sent

**Comment by WyrdWyn4** [comment]
> Thats already being sent

Oh my bad Boss. Thanks for letting me know

**Review by WyrdWyn4 — APPROVED** [review]
Great Work Boss!

**Review by AbdulTur — APPROVED** [review]
LGTM

**Pull request merged**
